export const columns = [
  {
    title: "Affidavit No",
    field: "affidavitNo",
    emptyValue: "-",
    type: "string",
    width: "120px",
  },
  {
    title: "Policy No",
    field: "policyNo",
    emptyValue: "-",
    type: "string",
    width: "150px",
  },
  {
    title: "Insured Name",
    field: "insuredName",
    emptyValue: "-",
    type: "string",
    width: "200px",
  },
  {
    title: "Type",
    field: "type",
    emptyValue: "-",
    type: "string",
    width: "100px",
    align: "right",
  },
  {
    title: "Premium",
    field: "premium",
    emptyValue: "-",
    type: "currency",
    width: "150px",
  },
  {
    title: "Inception",
    field: "inception",
    emptyValue: "-",
    type: "date",
    width: "110px",
    align: "justify",
  },
  {
    title: "Expiration",
    field: "expiration",
    emptyValue: "-",
    type: "date",
    width: "110px",
    align: "right",
  },
  {
    title: "Batch",
    field: "batch",
    emptyValue: "-",
    type: "string",
    width: "100px",
    align: "center",
  },
  {
    title: "Submitted",
    field: "submitted",
    emptyValue: "-",
    type: "date",
    width: "110px",
    align: "left",
  },
];
